### ISSUE TITLE
ClassicOldSong -> TheNeuronProject

### ISSUE THREAD

**Issue by simon300000** [ClassicOldSong/ef.js.org#1]
看到网站上好多链接，还有readme里都是 ClassicOldSong/ef.js
但其实会变成 TheNeuronProject/ef.js
虽然有自动跳转，但是还是可以改掉的www

**Comment by ClassicOldSong** [comment]
有空官网要重构了😂
现在多了很多东西，而且原版官网写得也比较糊，重构的时候一起改掉好了

**Comment by simon300000** [comment]
哇
